# 公共配置
server:
  # 当前服务的对外发布的端口
  port: 8101

# spring配置
spring:
  application:
    name: rbac-server
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/jwssw-base?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
      username: jwssw-base
      password: jwssw-base
      filters: stat,wall,log4j,config # 配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
      max-active: 100 # 最大连接数
      initial-size: 5 # 初始化大小
      max-wait: 60000 # 获取连接等待超时时间
      min-idle: 2 # 最小连接
  # consul服务发现和注册的配置
  consul:
    host: 127.0.0.1
    port: 8500
    discovery:
      # 注册到consul的服务名称
      serviceName: ${spring.application.name}
      # 强制使用IP地址的方式注册到consul上（这个必须配）
      prefer-ip-address: true

# spring security的配置
security:
  auth-server: http://localhost:8001
  # oauth2鉴权配置
  oauth2:
    # 客户端配置
    client:
      # 客户端用户名
      client-id: rbac-client
      # 客户端密钥
      client-secret: rbac-secret-8888
      # 用户跳转去获取access token的URI
      # user-authorization-uri: http://localhost:8001/oauth/authorize
      # 指定获取access token的URI
      # access-token-uri: http://localhost:8001/oauth/token
    # 访问URI资源的信息
    resource:
      user-info-uri: ${security.auth-server}/oauth/user
    # 授权配置
    authorization:
      # 检查token是否有效的连接（todo 是否可以通过api网关或者授权服务的集群配置）
      check-token-access: ${security.auth-server}/oauth/check_token

# 管理HTTP服务器（管理服务器属性）
# 在Spring Boot 2.0 中对Actuator变动很大，默认只提供这三个接口（/actuator、/actuator/health和/actuator/info），
# 要想暴露所有端点只需设置成星号即可（打开注解接口）。
# management.endpoints.web.exposure.include: "*"